---
- name: clone repos
  git:
    repo: "{{ item.url }}"
    dest: "{{ item.path }}"
    accept_hostkey: true
    version: "{{ item.version | default('master') }}"
    update: "no"
    track_submodules: "{{ item.track_submodules | default('yes') }}"
  when: >-
    item.enabled | default(true) | bool is sameas true and item.clone_enabled |
    default(true) | bool is sameas true
  with_items: "{{ git_repos }}"

- name: fetch repos
  shell: "git fetch {{ item.fetch_args | default(git_fetch_args) }}"
  args:
    chdir: "{{ item.path }}"
  when: >-
    item.enabled | default(true) | bool is sameas true and item.fetch_enabled |
    default(true) | bool is sameas true
  with_items: "{{ git_repos }}"
  changed_when: false
  tags:
    - skip_ansible_lint

- name: git pull
  shell: "git pull"
  args:
    chdir: "{{ item.path }}"
  register: gitpull
  changed_when: "'Already up to date' not in gitpull.stdout"
  when: >-
    item.enabled | default(true) | bool is sameas true and item.pull_enabled |
    default(true) | bool is sameas true
  with_items: "{{ git_repos }}"
  tags:
    - skip_ansible_lint

- name: git push
  shell: "git push {{ item.push_args | default(git_push_args) }}"
  args:
    chdir: "{{ item.path }}"
  register: gitpush
  changed_when: "'Everything up-to-date' not in gitpush.stderr"
  when: >-
    item.enabled | default(true) | bool is sameas true and item.push_enabled |
    default(false) | bool is sameas true
  with_items: "{{ git_repos }}"
  tags:
    - skip_ansible_lint

- name: git push tags
  shell: "git push --tags"
  args:
    chdir: "{{ item.path }}"
  register: gitpush_tags
  changed_when: "'Everything up-to-date' not in gitpush_tags.stderr"
  when: >-
    item.enabled | default(true) | bool is sameas true and item.push_enabled |
    default(false) | bool is sameas true
  with_items: "{{ git_repos }}"
  tags:
    - skip_ansible_lint

- name: repo git config
  git_config:
    scope: local
    repo: "{{ item.0.path }}"
    state: "{{ item.1.state | default('present') }}"
    name: "{{ item.1.name }}"
    value: "{{ item.1.value }}"
  when: >-
    item.0.enabled | default(true) | bool is sameas true
  loop: "{{ lookup('subelements', git_repos, 'config', { 'skip_missing': true }, wantlist=true) }}"
