---
- name: Converge
  hosts: all
  vars:
    git_repos:
      - url: https://github.com/agl4/ansible-role-git-repos.git
        path: ~/src/github.com/agl4/set-options.git
        version: main
        push_enabled: false
        push_tags_enabled: false
        pull_enabled: true
        fetch_enabled: true
        config:
          - name: user.name
            value: Attila GOLONCSER123
          - name: user.email
            value: agl4123@example.com
      - url: https://github.com/agl4/ansible-role-git-repos.git
        path: ~/src/github.com/use-defaults.git
        push_enabled: false
        push_tags_enabled: false
        pull_enabled: true
        fetch_enabled: true
  roles:
    - agl4.git_repos
