---
- name: Converge
  hosts: all
  vars:
    git_repos:
      - url: https://github.com/agoloncser/ansible-role-git-repos.git
        path: ~/src/github.com/agoloncser/set-options.git
        version: master
        push_enabled: false
        pull_enabled: true
        fetch_enabled: true
        push_tags_enabled: true
        config:
          - name: user.name
            value: Attila GOLONCSER123
          - name: user.email
            value: agoloncser123@example.com
      - url: https://github.com/agoloncser/ansible-role-git-repos.git
        path: ~/src/github.com/use-defaults.git
        push_enabled: false
        pull_enabled: true
        fetch_enabled: true
        push_tags_enabled: false
  roles:
    - agoloncser.git_repos
