---
name: Molecule testing
on:
  push: {}
  pull_request: {}
  schedule:
    - cron: "12 6 * * *"
jobs:
  molecule:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        python_version: ["3.8"]
        experimental: [false]
        molecule_image:
          - agoloncser/docker-ansible-fedora31
          - agoloncser/docker-ansible-fedora32
          - agoloncser/docker-ansible-ubuntu1804
          - agoloncser/docker-ansible-ubuntu2004
          - agoloncser/docker-ansible-centos7
          - agoloncser/docker-ansible-centos8
          - agoloncser/docker-ansible-debian10
          - agoloncser/docker-ansible-debian11
        include:
          - python_version: "3.8"
            molecule_image: agoloncser/docker-ansible-fedora33
            experimental: true
          - python_version: "3.8"
            molecule_image: agoloncser/docker-ansible-ubuntu2010
            experimental: true

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: "${{ github.repository }}"

      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python_version }}

      - name: Install dependencies
        run: pip install ansible molecule yamllint docker ansible-lint

      - name: Use Node.js
        uses: actions/setup-node@v1

      - name: Install Prettier.js
        run: npm install --global prettier

      - name: Molecule test
        run: molecule test
        working-directory: "${{ github.repository }}"
        env:
          MOLECULE_IMAGE: ${{ matrix.molecule_image }}

      - name: Import to Galaxy
        uses: robertdebock/galaxy-action@1.0.3
        with:
          galaxy_api_key: ${{ secrets.galaxy_api_key }}
