---
name: Molecule
"on":
  push: {}
  pull_request: {}
jobs:
  molecule:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        molecule_image:
          - ghcr.io/agoloncser/docker-molecule-fedora:39
          - ghcr.io/agoloncser/docker-molecule-fedora:40
          - ghcr.io/agoloncser/docker-molecule-ubuntu:20.04
          - ghcr.io/agoloncser/docker-molecule-ubuntu:22.04

    steps:
      - uses: agl4/actions/ansible-role/.github/workflows/molecule.yml@main
        env:
          molecule_image: ${{ matrix.molecule_image }}
